homebrew_installed_packages:
  - git
  - exa
  - yt-dlp
  - fzf
  - wget
  - tmux
  - qrencode
  - httpie
  - fd
  - bat

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_apps:
  - google-chrome
  - rectangle
  - signal
  - visual-studio-code
  - spotify
  - firefox
  - iterm2
  - shottr
  - adobe-acrobat-reader
  - font-fira-code-nerd-font
  - linearmouse

# taken from https://github.com/geerlingguy/dotfiles/blob/master/.osx
macos_defaults:
  # Keyboard / Mouse

  # Disable natural scrolling
  - domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: bool
    value: false
  # Keyrepeat
  - domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 2
  - domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 25

  # Finder

  # New windows open home folder
  - domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: "PfHm"
  # Enables status bar
  - domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true
  # Shows all file extensions
  - domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
  # Disable the warning when changing a file extension
  - domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false
  # Avoid creating .DS_Store files on network volumes
  - domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
